In [14]:
from tensorflow.keras.preprocessing.text import one_hot

In [15]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [16]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [17]:
# Define the vocabulary size
voc_size = 10000

In [18]:
# One Hot Representation
one_hot_repr = [one_hot(word,voc_size) for word in sent]
one_hot_repr

[[5535, 7896, 7563, 2129],
 [5535, 7896, 7563, 2899],
 [5535, 4809, 7563, 3928],
 [9831, 4864, 6280, 6476, 3478],
 [9831, 4864, 6280, 6476, 1235],
 [6139, 5535, 3983, 7563, 8011],
 [883, 2040, 1921, 6476]]

In [19]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [20]:
import numpy as np

In [21]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5535 7896 7563 2129]
 [   0    0    0    0 5535 7896 7563 2899]
 [   0    0    0    0 5535 4809 7563 3928]
 [   0    0    0 9831 4864 6280 6476 3478]
 [   0    0    0 9831 4864 6280 6476 1235]
 [   0    0    0 6139 5535 3983 7563 8011]
 [   0    0    0    0  883 2040 1921 6476]]


In [22]:
# feature representation
dim = 10

In [31]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding

# Define sizes properly
voc_size = 10000       # must be > 0
dim = 100              # embedding vector size
sent_length = 120      # input length (sequence length)

# Build model
model = Sequential()
model.add(Embedding(input_dim=voc_size, output_dim=dim, input_length=sent_length))
model.compile(optimizer='adam', loss='mse')

# Force model to build
model.build(input_shape=(None, sent_length))

model.summary()


Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ (None, 120, 100)       │     1,000,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,000,000 (3.81 MB)

 Trainable params: 1,000,000 (3.81 MB)

 Non-trainable params: 0 (0.00 B)

In [32]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step


array([[[-0.04319166,  0.02704438,  0.0259954 , ...,  0.01127829,
          0.02926605, -0.00482393],
        [-0.04319166,  0.02704438,  0.0259954 , ...,  0.01127829,
          0.02926605, -0.00482393],
        [-0.04319166,  0.02704438,  0.0259954 , ...,  0.01127829,
          0.02926605, -0.00482393],
        ...,
        [-0.00066202, -0.02428677,  0.01729224, ...,  0.0357149 ,
          0.02247018,  0.02555952],
        [ 0.02657822,  0.0268564 ,  0.03347092, ..., -0.01682907,
          0.0145104 ,  0.00734771],
        [ 0.04908944, -0.03248572, -0.00251091, ..., -0.04725228,
         -0.03544005,  0.04761505]],

       [[-0.04319166,  0.02704438,  0.0259954 , ...,  0.01127829,
          0.02926605, -0.00482393],
        [-0.04319166,  0.02704438,  0.0259954 , ...,  0.01127829,
          0.02926605, -0.00482393],
        [-0.04319166,  0.02704438,  0.0259954 , ...,  0.01127829,
          0.02926605, -0.00482393],
        ...,
        [-0.00066202, -0.02428677,  0.01729224, ...,  